services:
  docker2mqtt:
    build:
      context: .
      platforms:
        - "linux/arm64"
    container_name: docker2mqtt
    env_file:
      - .env
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - my_shared_network
networks:
  my_shared_network:
    external: true
